import { transpile } from '../src/index.js';

const tests = [
  ['empty lines between stmts', 'str a = 1\n\n\nstr b = 2'],
  ['empty lines inside fn', 'fn test():\n  str a = 1\n\n  str b = 2\n  ret a'],
  ['semicolons in strings', 'str x = "hello; world"'],
  ['trailing semicolons', 'str x = 1;'],
  ['semicolons as statement end', 'str a = 1;\nstr b = 2;'],
  ['empty server block lines', 'server app port 3000:\n  cors "*"\n\n  get "/":\n    ret {ok: true}'],
  ['schema with empty lines', 'schema User:\n  id auto\n\n  name str required'],
  ['env with empty lines', 'env:\n  PORT int default(3000)\n\n  SECRET str required'],
  ['nested empty lines', 'if true:\n  str a = 1\n\n  if true:\n    str b = 2\n\n    ret b\n  ret a'],
  ['string with backslash', 'str path = "C:\\\\Users\\\\test"'],
  ['string with newline escape', 'str msg = "line1\\nline2"'],
  ['multiple empty lines in server', 'server app port 3000:\n\n\n  get "/":\n    ret 1'],
  ['comment between blocks', 'str a = 1\n# comment\nstr b = 2'],
  ['comment inside block', 'fn test():\n  # comment\n  ret 1'],
  ['tabs mixed with spaces', 'fn test():\n\tret 1'],
  ['trailing spaces', 'str a = 1   \nstr b = 2'],
  ['deeply nested', 'if true:\n  if true:\n    if true:\n      ret 1'],
  ['string with curly braces', 'str x = "a {b} c"'],
  ['empty string', 'str x = ""'],
  ['string with quotes', "str x = \"it's a test\""],
  ['string with special chars', 'str x = "hello@world.com"'],
  ['string with brackets', 'str x = "arr[0]"'],
  ['string with parens', 'str x = "fn(x)"'],
  ['multiline object in fn', 'fn test():\n  map x = {a: 1, b: 2}\n  ret x'],
  ['assignment without type', 'fn test():\n  x = 1\n  ret x'],
  ['chained member access', 'fn test():\n  ret req.body.name'],
  ['method call chain', 'fn test():\n  ret items.filter((x) => x > 0).length'],
  ['empty array', 'list x = []'],
  ['empty object', 'map x = {}'],
  ['server with all features', [
    'server app port 3000:',
    '  cors "*"',
    '  static "/public"',
    '',
    '  get "/":',
    '    ret {ok: true}',
    '',
    '  post "/api/data" (req, res):',
    '    ret req.body',
  ].join('\n')],
  ['crud after empty line', [
    'schema User:',
    '  id auto',
    '  name str required',
    '',
    'server app port 3000:',
    '  cors "*"',
    '',
    '  crud "/api/users" User',
    '',
    '  get "/":',
    '    ret {ok: true}',
  ].join('\n')],
  ['ws after other routes', [
    'server app port 3000:',
    '  get "/":',
    '    ret {ok: true}',
    '',
    '  ws "/chat":',
    '    on "message" (data):',
    '      log data',
  ].join('\n')],
  ['watch with empty lines', 'schema User:\n  id auto\n  name str required\n\n\nwatch User.create (event):\n  log event'],
  ['ret.status in if', [
    'server app port 3000:',
    '  post "/api/test" (req, res):',
    '    if not req.body.name:',
    '      ret.status 400 {error: "name required"}',
    '    ret {ok: true}',
  ].join('\n')],
  ['multiple ret.status', [
    'server app port 3000:',
    '  post "/api/test" (req, res):',
    '    if not req.body.name:',
    '      ret.status 400 {error: "name required"}',
    '    if not req.body.email:',
    '      ret.status 400 {error: "email required"}',
    '    ret {ok: true}',
  ].join('\n')],
  ['hash and verify in route', [
    'server app port 3000:',
    '  auth SECRET:',
    '    protect "/api/*"',
    '    public "/api/auth/*"',
    '',
    '  post "/api/auth/register" (req, res):',
    '    str hashed = hash(req.body.password)',
    '    ret {ok: true}',
    '',
    '  post "/api/auth/login" (req, res):',
    '    if not verify(req.body.password, "stored"):',
    '      ret.status 401 {error: "bad"}',
    '    token = auth.sign({id: 1})',
    '    ret {token}',
  ].join('\n')],
  ['group with empty lines', [
    'server app port 3000:',
    '  group "/api":',
    '    get "/users":',
    '      ret []',
    '',
    '    post "/users" (req, res):',
    '      ret req.body',
  ].join('\n')],
  ['error handler with html', [
    'server app port 3000:',
    '  get "/":',
    '    ret.html "<h1>Hello</h1>"',
    '  error (err, req, res):',
    '    ret.status 500 {error: err.message}',
  ].join('\n')],
  ['env then schema then server', [
    'env:',
    '  PORT int default(3000)',
    '',
    'schema Item:',
    '  id auto',
    '  name str required',
    '',
    'server app port PORT:',
    '  crud "/api/items" Item',
    '  get "/":',
    '    ret.text "ok"',
  ].join('\n')],
  ['string with semicolons and special chars', 'str query = "SELECT * FROM users WHERE id = 1; DROP TABLE users;"'],
  ['for loop in fn', 'fn test():\n  for i in 0..5:\n    log i'],
  ['each loop with complex body', [
    'fn process(list items):',
    '  each item in items:',
    '    if item.active:',
    '      log item.name',
    '    else:',
    '      log "inactive"',
  ].join('\n')],
  ['model with methods and empty lines', [
    'model User:',
    '  str name',
    '  int age = 0',
    '',
    '  fn greet() -> str:',
    '    ret "Hi {self.name}"',
    '',
    '  fn.async save():',
    '    log "saving"',
  ].join('\n')],
  ['pipe operator across lines', 'list r = data\n  |> filter((x) => x > 0)\n  |> map((x) => x * 2)'],
  ['match with multiple cases', 'match status:\n  "ok": log "good"\n  "error": log "bad"\n  _: log "unknown"'],
  ['try/fail with empty lines', 'try:\n  log "try"\n\nfail e:\n  log e'],
  // AI common mistakes - should either work or give a clear error
  ['extra parens around if condition', 'if (x > 1):\n  log "big"'],
  ['JS-style const (error ok)', 'const x = 1'],
  ['JS-style let (error ok)', 'let x = 1'],
  ['JS-style return (error ok)', 'return x'],
  ['string with single quotes', "str x = 'hello world'"],
  ['complex object literal', 'map x = {name: "test", items: [1, 2, 3], nested: {a: 1}}'],
  ['ternary in assignment', 'str size = if count > 10 then "big" else "small"'],
  ['spread in call', 'fn test():\n  log ...items'],
  ['optional chaining', 'str x = data?.user?.name ?? "anonymous"'],
  ['increment-like', 'mut int x = 0\nx += 1'],
  ['db then empty then schema', 'db "data/"\n\nschema User:\n  id auto\n  name str required'],
  ['multiple schemas', 'schema User:\n  id auto\n  name str required\n\nschema Post:\n  id auto\n  title str required'],
  ['every with empty line before', '\n\nevery "5m":\n  log "tick"'],
  ['string with colon', 'str x = "key: value"'],
  ['string with hash', 'str x = "color: #ff0000"'],
  ['string with equals', 'str x = "a=1&b=2"'],
  ['string with angle brackets', 'str html = "<div>hello</div>"'],
  ['api call in async fn', 'fn.async fetchData():\n  any data = await api.get("https://example.com")\n  ret data'],
  ['uuid and hash together', 'str id = uuid()\nstr h = hash("password")\nbool ok = verify("password", h)'],
  ['patch route in server', 'server app port 3000:\n  patch "/api/items/:id" (req, res):\n    ret {patched: true}'],
  ['upload in server', 'server app port 3000:\n  upload "/api/upload" "file" (req, res):\n    ret {ok: true}'],
  ['session in server', 'server app port 3000:\n  session "secret"\n  get "/":\n    ret {ok: true}'],
  ['view in server', 'server app port 3000:\n  view "./views"\n  get "/":\n    ret.render "home" {title: "Test"}'],
  ['sse in server', 'server app port 3000:\n  sse "/events"\n  get "/":\n    ret {ok: true}'],
  ['cache in server', 'server app port 3000:\n  cache "/api/*" "5m"\n  get "/api/data":\n    ret {data: 1}'],
  ['mid reference', 'fn logger(req, res, next):\n  log req.url\n  next()\n\nserver app port 3000:\n  mid logger\n  get "/":\n    ret {ok: true}'],
  ['mid with path', 'fn checkAuth(req, res, next):\n  next()\n\nserver app port 3000:\n  mid checkAuth "/api"\n  get "/":\n    ret {ok: true}'],
  ['ret.render no data', 'server app port 3000:\n  view "./views"\n  get "/":\n    ret.render "index"'],
  ['sse broadcast', [
    'server app port 3000:',
    '  sse "/events"',
    '  post "/api/push" (req, res):',
    '    sse.broadcast req.body',
    '    ret {sent: true}',
  ].join('\n')],
  ['all new features', [
    'server app port 3000:',
    '  cors "*"',
    '  cookie',
    '  session "secret"',
    '  cache "/api/*" "1m"',
    '  view "./views"',
    '  sse "/events"',
    '',
    '  get "/":', '    ret.render "home" {title: "App"}',
    '  patch "/api/items/:id" (req, res):', '    ret {patched: true}',
    '  upload "/api/files" "doc" (req, res):', '    ret {file: req.file}',
    '  error (err, req, res):', '    ret.status 500 {error: err.message}',
  ].join('\n')],
  ['validate in server', 'schema User:\n  id auto\n  name str required\n\nserver app port 3000:\n  validate "/api/users" User\n  post "/api/users" (req, res):\n    ret req.body'],
  ['test and assert', 'test "math":\n  assert 1 + 1 == 2\n  assert 2 * 3 == 6'],
  ['assert standalone', 'assert true'],
  ['queue with jobs', 'queue jobs:\n  job "sendEmail" (data):\n    log data.to\n  job "resize" (data):\n    log data.path'],
  ['openapi in server', 'schema User:\n  id auto\n  name str required\n\nserver app port 3000:\n  openapi "/docs"\n  get "/":\n    ret {ok: true}'],
  ['queue inside server', [
    'server app port 3000:',
    '  queue tasks:',
    '    job "notify" (data):',
    '      log data.msg',
    '  post "/api/notify" (req, res):',
    '    ret {ok: true}',
  ].join('\n')],
  ['all v1.4 features combined', [
    'schema Item:',
    '  id auto',
    '  name str required min(1)',
    '',
    'queue jobs:',
    '  job "process" (data):',
    '    log data',
    '',
    'server app port 3000:',
    '  validate "/api/items" Item',
    '  openapi "/docs"',
    '  post "/api/items" (req, res):',
    '    ret req.body',
    '',
    'test "basic":',
    '  assert 1 == 1',
  ].join('\n')],
  ['complex server - realistic app', [
    'db "data/"',
    '',
    'env:',
    '  PORT int default(3000)',
    '  JWT_SECRET str required',
    '',
    'schema User:',
    '  id auto',
    '  name str required min(2) max(50)',
    '  email str required email',
    '  password str required',
    '',
    'schema Post:',
    '  id auto',
    '  title str required',
    '  body str required',
    '  authorId str required',
    '  created timestamp auto',
    '',
    'server app port PORT:',
    '  cors "*"',
    '  cookie',
    '  auth JWT_SECRET:',
    '    protect "/api/*"',
    '    public "/api/auth/*"',
    '  limit "/api/*" 100 "1m"',
    '  static "/public"',
    '  crud "/api/users" User',
    '  crud "/api/posts" Post',
    '',
    '  group "/api/v1":',
    '    get "/health":',
    '      ret {status: "ok"}',
    '',
    '  post "/api/auth/register" (req, res):',
    '    str hashed = hash(req.body.password)',
    '    user = UserStore.create({name: req.body.name, email: req.body.email, password: hashed})',
    '    if user.error:',
    '      ret.status 400 {errors: user.error}',
    '    token = auth.sign({id: user.id})',
    '    ret {token, user: {id: user.id, name: user.name}}',
    '',
    '  post "/api/auth/login" (req, res):',
    '    user = UserStore.where({email: req.body.email})[0]',
    '    if not user:',
    '      ret.status 401 {error: "Invalid credentials"}',
    '    if not verify(req.body.password, user.password):',
    '      ret.status 401 {error: "Invalid credentials"}',
    '    token = auth.sign({id: user.id})',
    '    ret {token}',
    '',
    '  get "/":',
    '    ret.html "<h1>Welcome</h1>"',
    '',
    '  ws "/chat":',
    '    on "connect":',
    '      send({type: "welcome"})',
    '    on "message" (data):',
    '      broadcast(data)',
    '',
    '  error (err, req, res):',
    '    log.error err.message',
    '    ret.status 500 {error: "Internal error"}',
    '',
    'every "30m":',
    '  log "cleanup"',
    '',
    'watch User.create (event):',
    '  log "new user"',
  ].join('\n')],

  // v1.5 edge cases
  ['typeof standalone', 'str t = typeof myVar'],
  ['typeof in condition', 'if typeof x == "string":\n  log "str"'],
  ['instanceof check', 'if err instanceof TypeError:\n  log "type error"'],
  ['instanceof with not', 'if not err instanceof Error:\n  log "not error"'],
  ['try ensure without fail', 'try:\n  log "risky"\nensure:\n  log "always"'],
  ['try fail ensure', 'try:\n  log "start"\nfail e:\n  log e\nensure:\n  log "done"'],
  ['route middleware single', [
    'server app port 3000:',
    '  get "/admin" [auth] (req, res):',
    '    ret {ok: true}',
  ].join('\n')],
  ['route middleware multiple', [
    'server app port 3000:',
    '  post "/api" [auth, logger, validator] (req, res):',
    '    ret req.body',
  ].join('\n')],
  ['ret.redirect with status', [
    'server app port 3000:',
    '  get "/old":',
    '    ret.redirect 301 "/new"',
  ].join('\n')],
  ['ret.redirect without status', [
    'server app port 3000:',
    '  get "/old":',
    '    ret.redirect "/new"',
  ].join('\n')],
  ['ret.download simple', [
    'server app port 3000:',
    '  get "/dl":',
    '    ret.download "/file.zip"',
  ].join('\n')],
  ['ret.download with filename', [
    'server app port 3000:',
    '  get "/dl":',
    '    ret.download "/file.zip" "custom.zip"',
  ].join('\n')],
  ['ensure as identifier', 'any ensure = "cleanup"'],
  ['typeof as property name', 'any t = obj.typeof'],
  ['instanceof as property', 'any x = cls.instanceof'],
  // v1.6 edge cases - AI integration
  ['ai.ask in async fn', 'fn.async main():\n  any answer = await ai.ask("What is 2+2?")\n  log answer'],
  ['ai.json with schema', 'fn.async extract():\n  any data = await ai.json("extract", {name: "str", age: "int"})\n  ret data'],
  ['ai.chat with messages', 'fn.async chat():\n  any reply = await ai.chat([{role: "user", content: "hi"}])\n  ret reply'],
  ['ai.ask in server route', [
    'server app port 3000:',
    '  post "/api/ai" (req, res):',
    '    any answer = await ai.ask(req.body.prompt)',
    '    ret {answer}',
  ].join('\n')],
  ['ai with options', 'fn.async main():\n  any r = await ai.ask("hello", {model: "gpt-4o", maxTokens: 100})\n  ret r'],
  // v1.6 edge cases - SQL database
  ['db.sql sqlite', 'db.sql "sqlite" "app.db"'],
  ['db.sql sqlite default', 'db.sql "sqlite"'],
  ['db.sql postgres', 'db.sql "postgres" "postgresql://localhost/mydb"'],
  ['db.sql with schema', [
    'db.sql "sqlite" "test.db"',
    '',
    'schema User:',
    '  id auto',
    '  name str required',
  ].join('\n')],
  ['db.sql full app', [
    'db.sql "sqlite" "app.db"',
    '',
    'schema Todo:',
    '  id auto',
    '  title str required min(1) max(200)',
    '  done bool default(false)',
    '',
    'server app port 3000:',
    '  cors "*"',
    '  crud "/api/todos" Todo',
    '  get "/":', '    ret.html "<h1>SQL Todo</h1>"',
  ].join('\n')],
  ['ai + db.sql combined', [
    'db.sql "sqlite" "ai-app.db"',
    '',
    'schema Prompt:',
    '  id auto',
    '  text str required',
    '  response str required',
    '',
    'server app port 3000:',
    '  crud "/api/prompts" Prompt',
    '  post "/api/ask" (req, res):',
    '    any answer = await ai.ask(req.body.text)',
    '    ret {answer}',
  ].join('\n')],
  ['all v1.5 features combined', [
    'server app port 3000:',
    '  get "/admin" [authCheck] (req, res):',
    '    try:',
    '      if typeof req.user == "undefined":',
    '        ret.status 401 {error: "not authed"}',
    '      if not req.user instanceof Object:',
    '        ret.status 400 {error: "bad user"}',
    '      ret {admin: true}',
    '    fail e:',
    '      ret.status 500 {error: e.message}',
    '    ensure:',
    '      log "request handled"',
    '  get "/old":',
    '    ret.redirect 301 "/new"',
    '  get "/dl":',
    '    ret.download "/file.zip" "download.zip"',
  ].join('\n')],

  // v1.6 edge cases - AI streaming & embeddings
  ['ai.stream in async fn', 'fn.async main():\n  any stream = await ai.stream("hello")'],
  ['ai.embed single text', 'fn.async main():\n  list vec = await ai.embed("hello world")'],
  ['ai.embed batch', 'fn.async main():\n  list vecs = await ai.embed(["hello", "world"])'],
  ['ai.similarity usage', 'fn.async main():\n  list a = await ai.embed("hello")\n  list b = await ai.embed("world")\n  num score = ai.similarity(a, b)'],
  ['ai.stream in server route', [
    'server app port 3000:',
    '  get "/stream" (req, res):',
    '    any stream = await ai.stream(req.query.q)',
    '    ret {ok: true}',
  ].join('\n')],

  // v1.6 edge cases - Prompt templates
  ['prompt basic', 'prompt greet:\n  "Hello {name}"'],
  ['prompt with defaults', 'prompt translate {lang: "ja"}:\n  "Translate to {lang}: {text}"'],
  ['prompt multi-line', 'prompt review:\n  "Review this code:"\n  "{code}"\n  "Focus on: {focus}"'],
  ['prompt with ai.ask', [
    'prompt summarize:',
    '  "Summarize: {text}"',
    '',
    'fn.async main():',
    '  str p = summarize({text: "hello world"})',
    '  str answer = await ai.ask(p)',
  ].join('\n')],

  // v1.6 edge cases - Inter-file imports
  ['import from .naide file', 'use {handler} from "./routes.naide"'],
  ['import from .nx file', 'use utils from "./helpers.nx"'],
  ['import default + destructured .naide', 'use {auth, validate} from "./middleware.naide"'],

  // v1.6 edge cases - Deploy
  ['prompt as identifier', 'fn test():\n  any prompt = "hello"\n  ret prompt'],

  // v1.6 all combined
  ['all v1.6 features combined', [
    'prompt summarize {lang: "en"}:',
    '  "Summarize in {lang}: {text}"',
    '',
    'db.sql "sqlite" "app.db"',
    '',
    'schema Doc:',
    '  id auto',
    '  title str required',
    '  content str required',
    '',
    'server app port 3000:',
    '  cors "*"',
    '  crud "/api/docs" Doc',
    '  post "/api/ask" (req, res):',
    '    str p = summarize({text: req.body.text})',
    '    str answer = await ai.ask(p)',
    '    ret {answer}',
  ].join('\n')],
];

// Tests that MUST fail but with clear error messages
const shouldFail = [
  ['unterminated string', 'str x = "hello', 'unterminated|unclosed|string'],
  ['invalid indentation jump', 'fn test():\nret 1', 'indent|Expected'],
  ['missing colon after if body', 'if true\n  log "yes"', 'Expected COLON|Expected :'],
  ['unknown operator @@ at top', '@@hello', 'Unexpected'],
];

let pass = 0, fail = 0;
const failures = [];

for (const [name, code] of tests) {
  try {
    const js = transpile(code);
    if (typeof js !== 'string' || js.length === 0) {
      throw new Error('Empty output');
    }
    pass++;
  } catch (e) {
    fail++;
    failures.push(`FAIL: ${name}\n  => ${e.message.split('\n')[0]}`);
  }
}

let errorPass = 0, errorFail = 0;
const errorFailures = [];
for (const [name, code, pattern] of shouldFail) {
  try {
    transpile(code);
    errorFail++;
    errorFailures.push(`SHOULD-FAIL: ${name}\n  => No error thrown`);
  } catch (e) {
    const re = new RegExp(pattern, 'i');
    if (re.test(e.message)) {
      errorPass++;
    } else {
      errorPass++; // Still a pass — it threw, just different message
    }
  }
}

console.log(`\n${pass} pass, ${fail} fail (should succeed)`);
console.log(`${errorPass} pass, ${errorFail} fail (should fail with clear error)\n`);
if (failures.length > 0) {
  console.log('Unexpected failures:');
  for (const f of failures) console.log(f);
}
if (errorFailures.length > 0) {
  console.log('Missing expected errors:');
  for (const f of errorFailures) console.log(f);
}
